_BASE_: [
  '../../ppyoloe/ppyoloe_plus_crn_m_80e_coco.yml',
]

# teacher pretrain model
pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_m_80e_coco.pdparams

slim: Distill
slim_method: LD

depth_mult: 0.33
width_mult: 0.50
